<?php 
	include("views/modules/head.php"); 
	include("views/modules/public/login-modal.php");
	include("views/modules/public/header.php");
	include("views/modules/public/slide.php");
	include("views/modules/public/news.php"); 
	include("views/modules/public/footer.php");
	include("views/modules/foot.php"); 
?>